metadata: {}
pipelines:
  ? ''
  : envs:
    - host
    path: pipelines/datapackage/
    stages:
    - run
    - update-datapackage
  blis:
    envs:
    - host
    path: pipelines/blis
    stages:
    - run
  datapackage:
    envs:
    - host
    path: pipelines/datapackage
    stages:
    - run
    - update-datapackage
popperized:
- github/popperized
