metadata: {}
pipelines:
  blis:
    envs:
    - host
    path: pipelines/blis
    stages:
    - run
  datapackage:
    envs:
    - host
    path: pipelines/datapackage
    stages:
    - run
    - update-datapackage
popperized:
- github/popperized
