- hosts: all
  tasks:
  - name: check for variables
    assert:
      that: 'threads is defined'

  - name: run wrf
    include: run_wrf.yml num_threads={{item}} flags_for_docker='-v `pwd`/results/:/wrfoutput'
    with_items: '{{ threads }}'

  - name: create results folder if it doesn't exist
    local_action:
      module: file
      path: '{{ results_path }}/{{ inventory_hostname }}'
      state: directory
      mode: 0755

  - name: fetch result files to compare
    synchronize:
      mode: pull
      src: /tmp/wrf/output/
      dest: '{{ results_path }}/{{ inventory_hostname }}/'

  - name: create facts folder if it doesn't exist
    local_action:
      module: file
      path: ./facts
      state: directory
      mode: 0755
    run_once: true

  - name: store facts about remotes
    local_action:
      module: copy
      content: '{{ hostvars[item] | to_nice_json }}'
      dest: './facts/{{ item }}.json'
    run_once: true
    with_items: '{{ groups.all }}'
